### ISSUE TITLE
Conceptos.María.Lizbeth.Bautista.García.1'A'

### ISSUE THREAD

**Issue by BautistaLizbeth** [SistemasTecTlaxiaco/actividad-4-mapa-mental-BautistaLizbeth#2]
[Conjuntos_María_Lizbeth_1'A'_20240921_141628_0000.pdf](https://github.com/user-attachments/files/17085642/Conjuntos_Maria_Lizbeth_1.A._20240921_141628_0000.pdf)

**Comment by josealfredo79** [comment]
Calificacion..???

**Comment by JordanMendoza401** [comment]
Manejo conceptual y dominio del tema 25/25
Relación entre los conceptos incluidos en el mapa 25/25
Calidad de la presentación 25/25
Jerarquía 25/25
CALIFICACION: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
